# About Dataset:

columns correction:
1. Reference Number: 2018 reference number have error "Accident Fields_Reference Number" is replace by "Reference Number"
2. Easting & Northing: 9,10,11,12 ma "Easting" relace by "Grid Ref: Easting" similar with Northing.
3. Number of Vehicles: corrected columns in all dataframe.
4. Accident_Date & Time(24hr): corrected columns
5. Extra columns name EXP1 has different columns
6. 1st Road class is not present in 2017 dataframe.
7. 1st road class& No is present in 2017,18, 18
8. road Surface is proper in all columns
9. lighting conditions, weather class, casuality class is proper in all class.
10. causuality severity, sex of casuality, age of casualty
11. type of vehicle
12. in year 2013 column name "Unnamed: 15" is replace by type_of vehicle.
13. we can drop casuality class and rename the Unamed:11 by casuality_class



final columns = ["Reference Number", "Easting", "Northing","Number_of_Vehicle", "accident_date","Time(24hr)","1st road class", lighting_conditions", "weather_conditions", "Road_surface", "Casuality Class", "Causuality severity",  "sex of casuality", "type of Vehicle", age_of_casualty]

In [1]:
# importing the important libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_2009 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2009.csv", encoding='latin1')
df_2010 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2010.csv", encoding='latin1')
df_2011 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2011.csv", encoding='latin1')
df_2012 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2012.csv", encoding='latin1')
df_2013 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2013.csv",encoding='latin1')
df_2014 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2014.csv",encoding='latin1')
df_2015 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2015.csv",encoding='latin1')
df_2016 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2016.csv",encoding='latin1')
df_2017 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2017.csv",encoding='latin1')
df_2018 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2018.csv",encoding='latin1')
df_2019 = pd.read_csv(r"C:\Users\Sumeet Maheshwari\Desktop\data\road accident\2019.csv",encoding='latin1')

# Cleaning and Concating the data
 * handling unstructured data and converting into proper format for making final dataframe

In [3]:
df_2013.drop("Casualty Class", axis=1, inplace = True)

In [4]:
df_2013.rename(columns={"Unnamed: 11": "Casualty Class", "Unnamed: 15": "Type of Vehicle" }, inplace = True)

In [5]:
df_2014.drop("Casualty Class", axis=1, inplace = True)
df_2014.rename(columns={"Unnamed: 11": "Casualty Class" }, inplace = True)

In [6]:
df_2016.drop("Expr1", axis=1,inplace= True)

In [7]:
columns_drop = ['Vehicle Fields_Reference Number', 'Vehicle Number','Local Authority','Casualty Fields_Reference Number', 'Casualty Veh No']
df_2018.drop(columns=columns_drop, inplace= True)

In [8]:
df_2018.rename(columns={"Accident Fields_Reference Number": "Reference Number" }, inplace = True)
df_2009.rename(columns={"Easting":"Grid Ref: Easting", "Northing": "Grid Ref: Northing" },inplace = True)
df_2010.rename(columns={"Easting":"Grid Ref: Easting", "Northing": "Grid Ref: Northing" },inplace = True)
df_2011.rename(columns={"Easting":"Grid Ref: Easting", "Northing": "Grid Ref: Northing" },inplace = True)
df_2012.rename(columns={"Easting":"Grid Ref: Easting", "Northing": "Grid Ref: Northing" },inplace = True)

In [9]:
len(df_2018.columns)

16

In [10]:
columns_drop = ['Local Authority', 'Vehicle Number']
df_2019.drop(columns=columns_drop, inplace= True)

In [11]:
len(df_2019.columns)

16

In [12]:
lst = [df_2009,df_2010,df_2011,df_2012,df_2013,df_2014,df_2015,df_2016,df_2017,df_2018,df_2019]
df = pd.concat(lst)

In [14]:
# saving a file of new_df
df.to_csv("Road_Accident_Record", index= False)

In [29]:
import pandas as pd
import os
import requests
import zipfile

def process_csv(year, dataframe):
    if year == 2013:
        dataframe.drop("Casualty Class", axis=1, inplace=True)
        dataframe.rename(columns={"Unnamed: 11": "Casualty Class", "Unnamed: 15": "Type of Vehicle"}, inplace=True)
    elif year == 2014:
        dataframe.drop("Casualty Class", axis=1, inplace=True)
        dataframe.rename(columns={"Unnamed: 11": "Casualty Class"}, inplace=True)
    elif year == 2016:
        dataframe.drop("Expr1", axis=1, inplace=True)
    elif year == 2018:
        columns_drop = ['Vehicle Fields_Reference Number', 'Vehicle Number', 'Local Authority',
                        'Casualty Fields_Reference Number', 'Casualty Veh No']
        dataframe.drop(columns=columns_drop, inplace=True)
        dataframe.rename(columns={"Accident Fields_Reference Number": "Reference Number"}, inplace=True)
    elif year in [2009, 2010, 2011, 2012]:
        dataframe.rename(columns={"Easting": "Grid Ref: Easting", "Northing": "Grid Ref: Northing"}, inplace=True)
        #columns_drop = ['Local Authority', 'Vehicle Number']
        #dataframe.drop(columns=columns_drop, inplace=True)
    elif year == 2019:
        columns_drop = ['Local Authority', 'Vehicle Number']
        dataframe.drop(columns=columns_drop, inplace=True)

def download_and_process_zip(url, output_csv_path):
    response = requests.get(url)
    if response.status_code != 200:
        print("Failed to download the zip file.")
        return
    
    with open("temp.zip", "wb") as zip_file:
        zip_file.write(response.content)
    with zipfile.ZipFile("temp.zip", 'r') as zip_ref:
        zip_ref.extractall("temp")
    os.remove("temp.zip")

    # Find the nested folder within the extracted directory
    extracted_folders = os.listdir("temp")
    if not extracted_folders:
        print("No folders found in the extracted directory.")
        return

    folder_path = os.path.join("temp", extracted_folders[0])

    # Process CSV files after extraction
    dfs = []
    csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
    print("Found CSV files:", csv_files)
    if not csv_files:
        print("No CSV files found in the extracted directory.")
        return
    
    for filename in csv_files:
        year = int(filename.split(".")[0])
        df = pd.read_csv(os.path.join(folder_path, filename), encoding = "latin1")
        process_csv(year, df)
        dfs.append(df)

    # Concatenate all dataframes into a single dataframe
    combined_df = pd.concat(dfs, ignore_index=True)

    # Save the combined dataframe to a single CSV file
    combined_df.to_csv(output_csv_path, index=False)

    # Clean up temporary directory
    os.rmdir("temp")

def main():
    github_zip_url = "https://github.com/sumeet0701/data-dump/raw/main/road%20accident.zip"
    output_csv_path = "output.csv"

    # Download and process the zip file from GitHub
    download_and_process_zip(github_zip_url, output_csv_path)

if __name__ == "__main__":
    main()

Found CSV files: ['2009.csv', '2010.csv', '2011.csv', '2012.csv', '2013.csv', '2014.csv', '2015.csv', '2016.csv', '2017.csv', '2018.csv', '2019.csv']

OSError: [WinError 145] The directory is not empty: 'temp'

In [30]:
df = pd.read_csv("output.csv")

In [31]:
df

,Reference Number,Grid Ref: Easting,Grid Ref: Northing,Number of Vehicles,Accident Date,Time (24hr),1st Road Class,Road Surface,Lighting Conditions,Weather Conditions,Casualty Class,Casualty Severity,Sex of Casualty,Age of Casualty,Type of Vehicle,1st Road Class & No
0,3309,429093,436258,1,01-Jan-09,55,Unclassified,Dry,Darkness: street lights present and lit,Fine without high winds,Pedestrian,Slight,Male,44,Car,NaN
1,2609,434723,435534,1,02-Jan-09,2335,Unclassified,Dry,Darkness: street lights present and lit,Fine without high winds,Driver,Serious,Female,23,Car,NaN
2,2809,441173,433047,1,02-Jan-09,1645,Unclassified,Dry,Darkness: street lights present and lit,Fine without high winds,Pedestrian,Slight,Female,12,Car,NaN
3,3809,428487,431364,1,02-Jan-09,1723,A,Dry,Darkness: street lights present and lit,Fine without high winds,Pedestrian,Slight,Male,15,Car,NaN
4,3909,425928,435480,2,02-Jan-09,1350,Unclassified,Dry,Daylight: street lights present,Fine without high winds,Driver,Slight,Female,34,Car,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27535,6CU0181,442094,434619,1,30/12/2019,422,1,2,4,4,1,3,1,27,9,M1
27536,6CU0363,423019,437653,1,30/12/2019,1000,3,4,1,1,1,2,1,36,5,A65
27537,6CV0723,436853,442515,2,31/12/2019,1340,3,1,1,1,1,2,1,59,1,A58
27538,6CV1518,421466,433999,3,31/12/2019,1640,3,1,4,1,1,3,1,41,9,A647
27539,6CV1518,421466,433999,3,31/12/2019,1640,3,1,4,1,2,3,1,26,9,A647